library(dplyr)
y2015 <- read.csv("march-madness-analytics-2020/MPlayByPlay_Stage2/MEvents2015.csv")
y2016 <- read.csv("march-madness-analytics-2020/MPlayByPlay_Stage2/MEvents2016.csv")
y2017 <- read.csv("march-madness-analytics-2020/MPlayByPlay_Stage2/MEvents2017.csv")
y2018 <- read.csv("march-madness-analytics-2020/MPlayByPlay_Stage2/MEvents2018.csv")
play_by_play_training <- rbind(y2015, y2016, y2017, y2018)
players_played_each_game_training <- distinct(play_by_play_training, Season, DayNum, EventTeamID, EventPlayerID)
detach("package:dplyr", unload = TRUE)
library(plyr)
players_played_per_game_training <- count(players_played_each_game_training, c("Season", "DayNum", "EventTeamID"))
detach("package:plyr", unload = TRUE)
library(dplyr)
players_played_per_game_training <- rename(players_played_per_game_training, c(PlayersPlayed=freq))

y2019 <- read.csv("march-madness-analytics-2020/MPlayByPlay_Stage2/MEvents2019.csv")
players_played_each_game_testing <- distinct(y2019, Season, DayNum, EventTeamID, EventPlayerID)
detach("package:dplyr", unload = TRUE)
library(plyr)
players_played_per_game_testing <- count(players_played_each_game_testing, c("Season", "DayNum", "EventTeamID"))
detach("package:plyr", unload = TRUE)
library(dplyr)
players_played_per_game_testing <- rename(players_played_per_game_testing, c(PlayersPlayed=freq))